import type { Metadata } from "next";
import { Geist, Geist_Mono, Newsreader, Manrope } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ClientSessionProvider } from "@/components/ClientSessionProvider";
import { ToastContainer } from "@/components/ui/ToastContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <NavBar />
          {children}
          <Footer />
          <ToastContainer />
        </ClientSessionProvider>
      </body>
    </html>
  );
}
