import { featuredCars } from "@/types/CarsTypes";
import { Cars } from "@/types/Cars";

export const featCars: featuredCars[] = [
	{
		id: 1,
		album: {
			photo1: "/cars/shop-featured/lambo/lambo1.jpeg",
			photo2: "/cars/shop-featured/lambo/lambo2.jpeg",
			photo3: "/cars/shop-featured/lambo/lambo3.jpeg",
		},
		model: "Lamborghini Revuelto",
		info: "a 1,001-horsepower HPEV (High Performance Electrified Vehicle) plug-in hybrid, serving as the V12 flagship successor to the Aventador.",
		price: "Price On Request",
	},
	{
		id: 2,
		album: {
			photo1: "/cars/shop-featured/911/p1.jpg",
			photo2: "/cars/shop-featured/911/p2.jpg",
			photo3: "/cars/shop-featured/911/p3.jpg",
		},
		model: "Porsche 911 Carrera GTS ",
		info: "a revolutionary 'T-Hybrid' system, combining a new 3.6L flat-six engine with electric turbocharging to produce 532 hp and 449 lb-ft of torque",
		price: "315K",
	},
	{
		id: 3,
		album: {
			photo1: "/cars/shop-featured/am/am1.jpeg",
			photo2: "/cars/shop-featured/am/am2.jpg",
			photo3: "/cars/shop-featured/am/am3.jpeg",
		},
		model: "aston martin db11",
		info: "a high-performance grand tourer available as a V8 or V12 coupe and Performance (Volante)",
		price: "150K",
	},
];

export const carsData: Cars[] = [
	{
		id: 1,
		brand: "Porsche",
		badge: "Popular",
		model: "911 Turbo S",
		specs: "3.8L Twin-Turbo Flat-6, 640 HP",
		bodySilhouette: "Coupe",
		price: 120000,
		image: "/cars/shop-featured/911/p1.jpg",
		carAlbum: {
			photo1: "/cars/shop-featured/911/p1.jpg",
			photo2: "/cars/shop-featured/911/p2.jpg",
			photo3: "/cars/shop-featured/911/p3.jpg",
		},
	},
	{
		id: 2,
		brand: "Ferrari",
		badge: "Top Speed",
		model: "F8 Tributo",
		specs: "3.9L V8 Twin-Turbo, 710 HP",
		bodySilhouette: "Coupe",
		price: 280000,
		carAlbum: {
			photo1: "/cars/ferrari/f8-1.jpg",
			photo2: "/cars/ferrari/f8-2.jpg",
			photo3: "/cars/ferrari/f8-3.jpg",
		},
	},
	{
		id: 3,
		brand: "Mercedes",
		badge: "Eco-Friendly",
		model: "EQS 580",
		specs: "Dual Electric Motors, 516 HP",
		bodySilhouette: "Electric",
		price: 95000,
		carAlbum: {
			photo1: "/cars/mercedes/sclass-1.jpg",
			photo2: "/cars/mercedes/sclass-2.jpg",
			photo3: "/cars/mercedes/sclass-3.jpg",
		},
	},
	{
		id: 4,
		brand: "Audi",
		badge: "Spacious",
		model: "Q8",
		specs: "3.0L V6 Turbo, 335 HP",
		bodySilhouette: "SUV",
		price: 80000,
		carAlbum: {
			photo1: "/cars/audi/q8-1.jpg",
			photo2: "/cars/audi/q8-2.jpg",
			photo3: "/cars/audi/q8-3.jpg",
		},
	},
	{
		id: 5,
		brand: "BMW",
		badge: "New Arrival",
		model: "i4 M50",
		specs: "Dual Electric Motors, 536 HP",
		bodySilhouette: "Electric",
		price: 70000,
		carAlbum: {
			photo1: "/cars/bmw/m5-1.jpg",
			photo2: "/cars/bmw/m5-2.jpg",
			photo3: "/cars/bmw/m5-3.jpg",
		},
	},
	{
		id: 6,
		brand: "Bentley",
		badge: "Luxury",
		model: "Flying Spur Hybrid",
		specs: "2.9L V6 + Electric Motor, 536 HP",
		bodySilhouette: "Electric",
		price: 220000,
		carAlbum: {
			photo1: "/cars/bentley/flyingspur-1.jpg",
			photo2: "/cars/bentley/flyingspur-2.jpg",
			photo3: "/cars/bentley/flyingspur-3.jpg",
		},
	},
	{
		id: 7,
		brand: "Aston Martin",
		badge: "Elegant",
		model: "DB11",
		specs: "4.0L V8 Twin-Turbo, 503 HP",
		bodySilhouette: "Coupe",
		price: 180000,
		carAlbum: {
			photo1: "/cars/astonmartin/db11-1.jpg",
			photo2: "/cars/astonmartin/db11-2.jpg",
			photo3: "/cars/astonmartin/db11-3.jpg",
		},
	},
	{
		id: 8,
		brand: "Lamborghini",
		badge: "Iconic",
		model: "Huracan Evo",
		specs: "5.2L V10, 631 HP",
		bodySilhouette: "Coupe",
		price: 300000,
		carAlbum: {
			photo1: "/cars/lamborghini/huracan-1.jpg",
			photo2: "/cars/lamborghini/huracan-2.jpg",
			photo3: "/cars/lamborghini/huracan-3.jpg",
		},
	},
	{
		id: 9,
		brand: "Porsche",
		badge: "Family Sport",
		model: "Cayenne Turbo",
		specs: "4.0L V8 Twin-Turbo, 541 HP",
		bodySilhouette: "SUV",
		price: 90000,
		carAlbum: {
			photo1: "/cars/porsche/cayenne-1.jpg",
			photo2: "/cars/porsche/cayenne-2.jpg",
			photo3: "/cars/porsche/cayenne-3.jpg",
		},
	},
	{
		id: 10,
		brand: "Ferrari",
		badge: "Classic",
		model: "Roma",
		specs: "3.9L V8 Twin-Turbo, 612 HP",
		bodySilhouette: "Performance",
		price: 350000,
		carAlbum: {
			photo1: "/cars/ferrari/roma-1.jpg",
			photo2: "/cars/ferrari/roma-2.jpg",
			photo3: "/cars/ferrari/roma-3.jpg",
		},
	},
	{
		id: 11,
		brand: "Mercedes",
		badge: "Track Ready",
		model: "AMG GT",
		specs: "4.0L V8 Twin-Turbo, 523 HP",
		bodySilhouette: "Coupe",
		price: 140000,
		carAlbum: {
			photo1: "/cars/mercedes/amg-gt-1.jpg",
			photo2: "/cars/mercedes/amg-gt-2.jpg",
			photo3: "/cars/mercedes/amg-gt-3.jpg",
		},
	},
	{
		id: 12,
		brand: "Audi",
		badge: "Next Gen",
		model: "e-tron GT",
		specs: "Dual Electric Motors, 469 HP",
		bodySilhouette: "Electric",
		price: 85000,
		carAlbum: {
			photo1: "/cars/audi/rs7-1.jpg",
			photo2: "/cars/audi/rs7-2.jpg",
			photo3: "/cars/audi/rs7-3.jpg",
		},
	},
	{
		id: 13,
		brand: "BMW",
		badge: "Agile",
		model: "M4 Competition",
		specs: "3.0L Inline-6 Twin-Turbo, 503 HP",
		bodySilhouette: "Coupe",
		price: 110000,
		carAlbum: {
			photo1: "/cars/bmw/m4-1.jpg",
			photo2: "/cars/bmw/m4-2.jpg",
			photo3: "/cars/bmw/m4-3.jpg",
		},
	},
	{
		id: 14,
		brand: "Bentley",
		badge: "Refined",
		model: "Continental GT",
		specs: "6.0L W12 Twin-Turbo, 626 HP",
		bodySilhouette: "Coupe",
		price: 250000,
		carAlbum: {
			photo1: "/cars/bentley/continental-1.jpg",
			photo2: "/cars/bentley/continental-2.jpg",
			photo3: "/cars/bentley/continental-3.jpg",
		},
	},
	{
		id: 15,
		brand: "Aston Martin",
		badge: "Powerful SUV",
		model: "DBX707",
		specs: "4.0L V8 Twin-Turbo, 697 HP",
		bodySilhouette: "SUV",
		price: 160000,
		carAlbum: {
			photo1: "/cars/astonmartin/dbx-1.jpg",
			photo2: "/cars/astonmartin/dbx-2.jpg",
			photo3: "/cars/astonmartin/dbx-3.jpg",
		},
	},
	{
		id: 16,
		brand: "Lamborghini",
		badge: "Super SUV",
		model: "Urus Performante",
		specs: "4.0L V8 Twin-Turbo, 657 HP",
		bodySilhouette: "SUV",
		price: 230000,
		carAlbum: {
			photo1: "/cars/lamborghini/urus-1.jpg",
			photo2: "/cars/lamborghini/urus-2.jpg",
			photo3: "/cars/lamborghini/urus-3.jpg",
		},
	},
	{
		id: 17,
		brand: "Porsche",
		badge: "Electric Beast",
		model: "Taycan Turbo S",
		specs: "Dual Electric Motors, 750 HP",
		bodySilhouette: "Electric",
		price: 100000,
		carAlbum: {
			photo1: "/cars/porsche/taycan-1.jpg",
			photo2: "/cars/porsche/taycan-2.jpg",
			photo3: "/cars/porsche/taycan-3.jpg",
		},
	},
	{
		id: 18,
		brand: "Ferrari",
		badge: "Hybrid King",
		model: "SF90 Stradale",
		specs: "4.0L V8 + 3 Electric Motors, 986 HP",
		bodySilhouette: "Coupe",
		price: 320000,
		carAlbum: {
			photo1: "/cars/ferrari/sf90-1.jpg",
			photo2: "/cars/ferrari/sf90-2.jpg",
			photo3: "/cars/ferrari/sf90-3.jpg",
		},
	},
	{
		id: 19,
		brand: "Mercedes",
		badge: "Premium",
		model: "GLE 53 AMG",
		specs: "3.0L Inline-6 Turbo, 429 HP",
		bodySilhouette: "SUV",
		price: 125000,
		carAlbum: {
			photo1: "/cars/mercedes/gle-1.jpg",
			photo2: "/cars/mercedes/gle-2.jpg",
			photo3: "/cars/mercedes/gle-3.jpg",
		},
	},
	{
		id: 20,
		brand: "Audi",
		badge: "Last of V10",
		model: "R8 V10 Performance",
		specs: "5.2L V10, 602 HP",
		bodySilhouette: "Coupe",
		price: 150000,
		carAlbum: {
			photo1: "/cars/audi/r8-1.jpg",
			photo2: "/cars/audi/r8-2.jpg",
			photo3: "/cars/audi/r8-3.jpg",
		},
	},
	{
		id: 21,
		brand: "BMW",
		bodySilhouette: "SUV",
		price: 90000,
		carAlbum: {
			photo1: "/cars/bmw/x6-1.jpg",
			photo2: "/cars/bmw/x6-2.jpg",
			photo3: "/cars/bmw/x6-3.jpg",
		},
	},
	{
		id: 22,
		brand: "Bentley",
		bodySilhouette: "SUV",
		price: 210000,
		carAlbum: {
			photo1: "/cars/bentley/bentayga-1.jpg",
			photo2: "/cars/bentley/bentayga-2.jpg",
			photo3: "/cars/bentley/bentayga-3.jpg",
		},
	},
	{
		id: 23,
		brand: "Aston Martin",
		bodySilhouette: "Coupe",
		price: 200000,
		carAlbum: {
			photo1: "/cars/astonmartin/vantage-1.jpg",
			photo2: "/cars/astonmartin/vantage-2.jpg",
			photo3: "/cars/astonmartin/vantage-3.jpg",
		},
	},
	{
		id: 24,
		brand: "Lamborghini",
		bodySilhouette: "Performance",
		price: 340000,
		carAlbum: {
			photo1: "/cars/lamborghini/aventador-1.jpg",
			photo2: "/cars/lamborghini/aventador-2.jpg",
			photo3: "/cars/lamborghini/aventador-3.jpg",
		},
	},
	{
		id: 25,
		brand: "BMW",
		bodySilhouette: "Electric",
		price: 60000,
		carAlbum: {
			photo1: "/cars/bmw/series3-1.jpg",
			photo2: "/cars/bmw/series3-2.jpg",
			photo3: "/cars/bmw/series3-3.jpg",
		},
	},
];
